name: mustika_farm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  go_router: ^13.2.1
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: fonts/AirbnbCerealBlack.ttf
          weight: 900
        - asset: fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: fonts/AirbnbCerealMedium.ttf
          weight: 500
